# SPDX-License-Identifier: GPL-2.0-only

apple-y := apple_drv.o
apple_dcp-y := dcp.o parser.o
apple_piodma-y := dummy-piodma.o

obj-$(CONFIG_DRM_APPLE) += apple.o
obj-$(CONFIG_DRM_APPLE) += apple_dcp.o
obj-$(CONFIG_DRM_APPLE) += apple_piodma.o
